In [1]:
from fac_reducao_cosseno import (
    montar_base_fac,
    executar_experimento,
    imprimir_resultados,
)

df = montar_base_fac()

resultados = executar_experimento(
    df,
    seed=42,
)

imprimir_resultados(resultados)

RESUMO
                     METRICA   VALOR
                        SEED   42.00
           JOGOS_PROCESSADOS  156.00
     JOGOS_COM_ALVO_ORIGINAL  149.00
     JOGOS_SEM_ALVO_ORIGINAL    7.00
            GRUPOS_ORIGINAIS 3432.00
               GRUPOS_FINAIS  936.00
             ALVOS_ORIGINAIS  272.00
         ALVOS_SOBREVIVENTES   70.00
        JOGOS_COM_ALVO_FINAL   59.00
        HIT6_CONDICIONAL_PCT   39.60
    BASELINE_CONDICIONAL_PCT   42.17
        GANHO_CONDICIONAL_PP   -2.58
        HIT6_TODOS_JOGOS_PCT   37.82
    BASELINE_TODOS_JOGOS_PCT   40.28
            RECALL_ALVOS_PCT   25.74
         ACE_MAX_FINAL_MEDIO   13.25
JOGOS_COM_ACE_MAX_PRESERVADO   59.00

RODADAS
 RODADA  GRUPOS_RESTANTES  ALVOS_RESTANTES  JOGOS_COM_ALVO  HIT_CONDICIONAL_PCT
      0              3432              272             149               100.00
      1              2652              207             133                89.26
      2              2028              147             103                69.13
      3              1560              115              89                59.73
      4              1248               94              77                51.68
      5               936               70              59                39.60

DISTRIBUICAO_ACE
 ACE  ORIGINAIS  FINAIS
  10        198      60
  11        885     237
  12       1267     343
  13        810     226
  14        248      65
  15         24       5

In [3]:
from fac_reducao_cosseno import avaliar_sementes

repeticoes = avaliar_sementes(
    df,
    seeds=range(100),
)

colunas = [
    "HIT6_CONDICIONAL_PCT",
    "GANHO_CONDICIONAL_PP",
]

display(
    repeticoes[colunas]
    .agg(["mean", "std", "min", "max"])
    .round(2)
)

      HIT6_CONDICIONAL_PCT  GANHO_CONDICIONAL_PP
mean                 40.66                 -1.52
std                   4.00                  4.00
min                  32.89                 -9.29
max                  50.34                  8.16

### Calculo do Cosseno Baseado em Frequencia Relativa das DEZs

In [4]:
import importlib
import fac_reducao_cosseno as fac

importlib.reload(fac)

resultados = fac.executar_experimento(
    df,
    seed=42,
)

fac.imprimir_resultados(resultados)

METRICA: cosseno_frequencias_v2

RESUMO
                     METRICA   VALOR
                        SEED   42.00
           JOGOS_PROCESSADOS  156.00
     JOGOS_COM_ALVO_ORIGINAL  149.00
     JOGOS_SEM_ALVO_ORIGINAL    7.00
            GRUPOS_ORIGINAIS 3432.00
               GRUPOS_FINAIS  936.00
             ALVOS_ORIGINAIS  272.00
         ALVOS_SOBREVIVENTES   67.00
        JOGOS_COM_ALVO_FINAL   57.00
        HIT6_CONDICIONAL_PCT   38.26
    BASELINE_CONDICIONAL_PCT   42.17
        GANHO_CONDICIONAL_PP   -3.92
        HIT6_TODOS_JOGOS_PCT   36.54
    BASELINE_TODOS_JOGOS_PCT   40.28
            RECALL_ALVOS_PCT   24.63
         ACE_MAX_FINAL_MEDIO   13.25
JOGOS_COM_ACE_MAX_PRESERVADO   58.00

RODADAS
 RODADA  GRUPOS_RESTANTES  ALVOS_RESTANTES  JOGOS_COM_ALVO  HIT_CONDICIONAL_PCT
      0              3432              272             149               100.00
      1              2652              208             130                87.25
      2              2028              159             112                75.17
      3              1560              117              93                62.42
      4              1248               88              74                49.66
      5               936               67              57                38.26

DISTRIBUICAO_ACE
 ACE  ORIGINAIS  FINAIS
  10        198      55
  11        885     241
  12       1267     337
  13        810     236
  14        248      59
  15         24       8

In [5]:
repeticoes = fac.avaliar_sementes(
    df,
    seeds=range(100),
)

display(
    repeticoes[
        ["HIT6_CONDICIONAL_PCT", "GANHO_CONDICIONAL_PP"]
    ]
    .agg(["mean", "std", "min", "max"])
    .round(2)
)

      HIT6_CONDICIONAL_PCT  GANHO_CONDICIONAL_PP
mean                 40.82                 -1.36
std                   3.96                  3.96
min                  32.21                 -9.96
max                  49.66                  7.49

### Calculo do Cosseno baseada na Dezenas e na Freq. Relativas

In [12]:
import importlib
import fac_reducao_cosseno as fac

importlib.reload(fac)

resultados = fac.executar_experimento(df, seed=42)
fac.imprimir_resultados(resultados)

METRICA: media_cosseno_dezenas_frequencias_v3

RESUMO
                     METRICA   VALOR
                        SEED   42.00
           JOGOS_PROCESSADOS  156.00
     JOGOS_COM_ALVO_ORIGINAL  149.00
     JOGOS_SEM_ALVO_ORIGINAL    7.00
            GRUPOS_ORIGINAIS 3432.00
               GRUPOS_FINAIS  936.00
             ALVOS_ORIGINAIS  272.00
         ALVOS_SOBREVIVENTES   76.00
        JOGOS_COM_ALVO_FINAL   67.00
        HIT6_CONDICIONAL_PCT   44.97
    BASELINE_CONDICIONAL_PCT   42.17
        GANHO_CONDICIONAL_PP    2.79
        HIT6_TODOS_JOGOS_PCT   42.95
    BASELINE_TODOS_JOGOS_PCT   40.28
            RECALL_ALVOS_PCT   27.94
         ACE_MAX_FINAL_MEDIO   13.43
JOGOS_COM_ACE_MAX_PRESERVADO   72.00

RODADAS
 RODADA  GRUPOS_RESTANTES  ALVOS_RESTANTES  JOGOS_COM_ALVO  HIT_CONDICIONAL_PCT
      0              3432              272             149               100.00
      1              2652              214             132                88.59
      2              2028              157             113                75.84
      3              1560              117              93                62.42
      4              1248              100              83                55.70
      5               936               76              67                44.97

DISTRIBUICAO_ACE
 ACE  ORIGINAIS  FINAIS
  10        198      54
  11        885     255
  12       1267     335
  13        810     216
  14        248      69
  15         24       7

In [9]:
repeticoes = fac.avaliar_sementes(
    df,
    seeds=range(100),
)

display(
    repeticoes[
        ["HIT6_CONDICIONAL_PCT", "GANHO_CONDICIONAL_PP"]
    ]
    .agg(["mean", "std", "min", "max"])
    .round(2)
)

      HIT6_CONDICIONAL_PCT  GANHO_CONDICIONAL_PP
mean                 44.87                  2.69
std                   3.49                  3.49
min                  36.24                 -5.93
max                  52.35                 10.17

### Novo Metodo para Medir Distancia dos Quartetos

In [19]:
import fac_quartetos_distancia as fac_dist

resultados_dist = fac_dist.executar_experimento(
    df,
    seed=42,
)

fac_dist.imprimir_resultados(resultados_dist)

METRICA: quartetos_minimax_soma_remocao_cosseno_medio_v1

RESUMO
                       METRICA   VALOR
                          SEED   42.00
             JOGOS_PROCESSADOS  156.00
       JOGOS_COM_ALVO_ORIGINAL  149.00
       JOGOS_SEM_ALVO_ORIGINAL    7.00
              GRUPOS_ORIGINAIS 3432.00
                 GRUPOS_FINAIS  936.00
               ALVOS_ORIGINAIS  272.00
           ALVOS_SOBREVIVENTES   90.00
          JOGOS_COM_ALVO_FINAL   68.00
          HIT6_CONDICIONAL_PCT   45.64
      BASELINE_CONDICIONAL_PCT   42.17
          GANHO_CONDICIONAL_PP    3.46
          HIT6_TODOS_JOGOS_PCT   43.59
      BASELINE_TODOS_JOGOS_PCT   40.28
              RECALL_ALVOS_PCT   33.09
           ACE_MAX_FINAL_MEDIO   13.29
  JOGOS_COM_ACE_MAX_PRESERVADO   70.00
              BLOCOS_AVALIADOS 2496.00
    REMOCOES_COM_MENOR_ACE_PCT   47.24
         BLOCOS_COM_UNICO_ALVO  493.00
BLOCOS_QUE_PERDERAM_UNICO_ALVO  135.00

RODADAS
 RODADA  GRUPOS_RESTANTES  ALVOS_RESTANTES  JOGOS_COM_ALVO  HIT_CONDICIONAL_PCT
      0              3432              272             149               100.00
      1              2652              205             135                90.60
      2              2028              163             116                77.85
      3              1560              136             103                69.13
      4              1248              110              82                55.03
      5               936               90              68                45.64

DISTRIBUICAO_ACE
 ACE  ORIGINAIS  FINAIS
  10        198      61
  11        885     245
  12       1267     318
  13        810     222
  14        248      82
  15         24       8

In [20]:
###df = fac_dist.montar_base_fac()
####display(resultados_dist["diagnostico_blocos"].head())

In [15]:
repeticoes_dist = fac_dist.avaliar_sementes(
    df,
    seeds=range(100),
)

display(
    repeticoes_dist[
        ["HIT6_CONDICIONAL_PCT", "GANHO_CONDICIONAL_PP"]
    ]
    .agg(["mean", "std", "min", "max"])
    .round(2)
)

      HIT6_CONDICIONAL_PCT  GANHO_CONDICIONAL_PP
mean                 40.26                 -1.91
std                   2.61                  2.61
min                  34.90                 -7.28
max                  46.98                  4.81

#### Novo Metodo para Medir Distancia dos Quartetos - Removendo o Cosseno

In [21]:
import fac_quartetos_aleatorio as fac_aleat

repeticoes_aleat = fac_aleat.avaliar_sementes(
    df,
    seeds=range(100),
    progresso=10,
)

display(
    repeticoes_aleat[
        ["HIT6_CONDICIONAL_PCT", "GANHO_CONDICIONAL_PP"]
    ]
    .agg(["mean", "std", "min", "max"])
    .round(2)
)

Sementes concluídas: 10/100
Sementes concluídas: 20/100
Sementes concluídas: 30/100
Sementes concluídas: 40/100
Sementes concluídas: 50/100
Sementes concluídas: 60/100
Sementes concluídas: 70/100
Sementes concluídas: 80/100
Sementes concluídas: 90/100
Sementes concluídas: 100/100

      HIT6_CONDICIONAL_PCT  GANHO_CONDICIONAL_PP
mean                 44.04                  1.87
std                   3.80                  3.80
min                  35.57                 -6.60
max                  53.69                 11.52

### Testando a Hipotese usando ACE para ordenar os 22GPRs

In [22]:
import fac_diagnostico_ace as fac_diag

resultado_diag = fac_diag.executar_experimento(
    df,
    seed=42,
)

fac_diag.imprimir_resultados(resultado_diag)

METRICA: DIAGNOSTICO_ACE_DESC_REMOCAO_COSSENO_MEDIO
Diagnóstico com ACE conhecido: Hit@6 não mede capacidade preditiva.

RESUMO
                                   METRICA   VALOR
                                      SEED   42.00
                         JOGOS_PROCESSADOS  156.00
                   JOGOS_COM_ALVO_ORIGINAL  149.00
                   JOGOS_SEM_ALVO_ORIGINAL    7.00
                          GRUPOS_ORIGINAIS 3432.00
                             GRUPOS_FINAIS  936.00
                           ALVOS_ORIGINAIS  272.00
                       ALVOS_SOBREVIVENTES  123.00
                      JOGOS_COM_ALVO_FINAL   92.00
                      HIT6_CONDICIONAL_PCT   61.74
                  BASELINE_CONDICIONAL_PCT   42.17
                      GANHO_CONDICIONAL_PP   19.57
                      HIT6_TODOS_JOGOS_PCT   58.97
                  BASELINE_TODOS_JOGOS_PCT   40.28
                          RECALL_ALVOS_PCT   45.22
                       ACE_MAX_FINAL_MEDIO   13.62
              JOGOS_COM_ACE_MAX_PRESERVADO   93.00
                          BLOCOS_AVALIADOS 2496.00
                REMOCOES_COM_MENOR_ACE_PCT   71.79
                     BLOCOS_COM_UNICO_ALVO  378.00
            BLOCOS_QUE_PERDERAM_UNICO_ALVO   57.00
                BLOCOS_COM_ACES_DIFERENTES 1679.00
MENOR_ACE_REMOVIDO_BLOCOS_INFORMATIVOS_PCT   58.07
              BASELINE_LOCAL_MENOR_ACE_PCT   47.99
                  GANHO_LOCAL_MENOR_ACE_PP   10.08

RODADAS
 RODADA  GRUPOS_RESTANTES  ALVOS_RESTANTES  JOGOS_COM_ALVO  HIT_CONDICIONAL_PCT
      0              3432              272             149               100.00
      1              2652              212             132                88.59
      2              2028              178             121                81.21
      3              1560              148             109                73.15
      4              1248              131              99                66.44
      5               936              123              92                61.74

DISTRIBUICAO_ACE
 ACE  ORIGINAIS  FINAIS
  10        198     101
  11        885     283
  12       1267     180
  13        810     249
  14        248     111
  15         24      12

In [25]:
import fac_diagnostico_ace as fac_diag

repeticoes_diag = fac_diag.avaliar_sementes(
    df,
    seeds=range(100)
)

display(
    repeticoes_diag[
        ["HIT6_CONDICIONAL_PCT", "GANHO_CONDICIONAL_PP"]
    ]
    .agg(["mean", "std", "min", "max"])
    .round(2)
)

      HIT6_CONDICIONAL_PCT  GANHO_CONDICIONAL_PP
mean                 64.19                 22.01
std                   3.23                  3.23
min                  54.36                 12.19
max                  71.14                 28.97

### Remocao Aleatória após Ordenar por ACE

In [26]:
import types
import numpy as np
import pandas as pd
import fac_diagnostico_ace as fac_diag


def selecionar_grupos_aleatorio(
    grupos,
    grupo_ids,
    acertos,
    seed=42,
    jogo=0,
):
    if len(grupos) not in (16, 22):
        raise ValueError("Esperado 16 ou 22 grupos.")

    if len(grupo_ids) != len(grupos) or len(set(grupo_ids)) != len(grupos):
        raise ValueError("GRUPO_ID deve ser único por jogo.")

    for grupo in grupos:
        fac_diag.validar_grupo(grupo, 20, "GRUPO")

    acertos = np.asarray(acertos)

    if (
        acertos.shape != (len(grupos),)
        or not np.issubdtype(acertos.dtype, np.integer)
        or np.any((acertos < 10) | (acertos > 15))
    ):
        raise ValueError("Esperado um ACE inteiro entre 10 e 15 por grupo.")

    # Mesma semente de ordenação usada no diagnóstico por cosseno.
    rng_ordem = np.random.default_rng(
        np.random.SeedSequence([int(seed), int(jogo), 1])
    )

    # Sorteios de remoção independentes da ordenação.
    rng_remocao = np.random.default_rng(
        np.random.SeedSequence([int(seed), int(jogo), 2])
    )

    ativos = np.arange(len(grupos))
    auditoria = []
    rodada = 0

    while len(ativos) > 6:
        rodada += 1

        embaralhados = rng_ordem.permutation(ativos)
        ordem = embaralhados[
            np.argsort(-acertos[embaralhados], kind="stable")
        ]

        n_blocos = len(ordem) // 4
        limite = n_blocos * 4
        remover = set()

        for bloco in range(n_blocos):
            indices = ordem[4 * bloco:4 * bloco + 4]

            # Cada um dos quatro grupos tem 25% de chance de sair.
            excluido = int(rng_remocao.choice(indices))
            remover.add(excluido)

            for indice in indices:
                auditoria.append({
                    "RODADA": rodada,
                    "N_ANTES": len(ativos),
                    "N_DEPOIS": len(ativos) - n_blocos,
                    "BLOCO": bloco + 1,
                    "GRUPO_ID": grupo_ids[indice],
                    "PROB_REMOCAO": 0.25,
                    "REMOVIDO": int(indice) == excluido,
                    "SOBRA": False,
                })

        for indice in ordem[limite:]:
            auditoria.append({
                "RODADA": rodada,
                "N_ANTES": len(ativos),
                "N_DEPOIS": len(ativos) - n_blocos,
                "BLOCO": 0,
                "GRUPO_ID": grupo_ids[indice],
                "PROB_REMOCAO": 0.0,
                "REMOVIDO": False,
                "SOBRA": True,
            })

        ativos = np.array([
            i for i in ativos if int(i) not in remover
        ])

    return ativos, pd.DataFrame(auditoria)


# Reutiliza a avaliação anterior com o novo seletor, sem alterar
# o módulo nem interferir no teste por cosseno em andamento.
contexto_aleatorio = dict(fac_diag.executar_experimento.__globals__)
contexto_aleatorio["selecionar_grupos"] = selecionar_grupos_aleatorio

executar_aleatorio = types.FunctionType(
    fac_diag.executar_experimento.__code__,
    contexto_aleatorio,
    name="executar_aleatorio",
    argdefs=fac_diag.executar_experimento.__defaults__,
)


# Ordenação por ACE + remoção aleatória: 100 sementes.
linhas = []

for seed in range(100):
    resultado = executar_aleatorio(df, seed=seed)

    linhas.append(
        resultado["resumo"]
        .set_index("METRICA")["VALOR"]
        .to_dict()
    )

    if (seed + 1) % 10 == 0:
        print(f"Sementes concluídas: {seed + 1}/100", flush=True)

repeticoes_ace_aleatorio = pd.DataFrame(linhas)

display(
    repeticoes_ace_aleatorio[
        ["HIT6_CONDICIONAL_PCT", "GANHO_CONDICIONAL_PP"]
    ]
    .agg(["mean", "std", "min", "max"])
    .round(2)
)

Sementes concluídas: 10/100
Sementes concluídas: 20/100
Sementes concluídas: 30/100
Sementes concluídas: 40/100
Sementes concluídas: 50/100
Sementes concluídas: 60/100
Sementes concluídas: 70/100
Sementes concluídas: 80/100
Sementes concluídas: 90/100
Sementes concluídas: 100/100

      HIT6_CONDICIONAL_PCT  GANHO_CONDICIONAL_PP
mean                 38.00                 -4.17
std                   3.44                  3.44
min                  30.87                -11.30
max                  46.98                  4.81

#### Remoção usando Distância Euclidiana com relação ao Vetor com as 25 dezenas (Freq Relativa)

In [29]:
import fac_diagnostico_ace_euclidiana as fac_eucl

repeticoes_eucl = fac_eucl.avaliar_sementes(
    df,
    seeds=range(100),
    progresso=10,
)

display(
    repeticoes_eucl[
        ["HIT6_CONDICIONAL_PCT", "GANHO_CONDICIONAL_PP"]
    ]
    .agg(["mean", "std", "min", "max"])
    .round(2)
)

Sementes concluídas: 10/100
Sementes concluídas: 20/100
Sementes concluídas: 30/100
Sementes concluídas: 40/100
Sementes concluídas: 50/100
Sementes concluídas: 60/100
Sementes concluídas: 70/100
Sementes concluídas: 80/100
Sementes concluídas: 90/100
Sementes concluídas: 100/100

      HIT6_CONDICIONAL_PCT  GANHO_CONDICIONAL_PP
mean                 66.07                 23.89
std                   2.76                  2.76
min                  58.39                 16.21
max                  71.14                 28.97

#### Remoção usando Distância Euclidiana com relação ao Vetor com as 20 Top dezenas (Freq Relativa)

In [28]:
import fac_diagnostico_ace_euclidiana_top20 as fac_eucl20

repeticoes_eucl20 = fac_eucl20.avaliar_sementes(
    df,
    seeds=range(100),
    progresso=10,
)

display(
    repeticoes_eucl20[
        ["HIT6_CONDICIONAL_PCT", "GANHO_CONDICIONAL_PP"]
    ]
    .agg(["mean", "std", "min", "max"])
    .round(2)
)

Sementes concluídas: 10/100
Sementes concluídas: 20/100
Sementes concluídas: 30/100
Sementes concluídas: 40/100
Sementes concluídas: 50/100
Sementes concluídas: 60/100
Sementes concluídas: 70/100
Sementes concluídas: 80/100
Sementes concluídas: 90/100
Sementes concluídas: 100/100

      HIT6_CONDICIONAL_PCT  GANHO_CONDICIONAL_PP
mean                 66.59                 24.42
std                   2.90                  2.90
min                  60.40                 18.23
max                  73.83                 31.65

#### Remoção usando Distância Euclidiana com relação ao Vetor com as 20 Top dezenas (Freq Relativa)
#### Utilizando Cosseno como criterio de desempate

In [31]:
import fac_diagnostico_ace_top20_desempate_cosseno as fac_desempate

repeticoes_desempate = fac_desempate.avaliar_sementes(
    df,
    seeds=range(100),
    progresso=10,
)

display(
    repeticoes_desempate[
        ["HIT6_CONDICIONAL_PCT", "GANHO_CONDICIONAL_PP"]
    ]
    .agg(["mean", "std", "min", "max"])
    .round(2)
)

Sementes concluídas: 10/100
Sementes concluídas: 20/100
Sementes concluídas: 30/100
Sementes concluídas: 40/100
Sementes concluídas: 50/100
Sementes concluídas: 60/100
Sementes concluídas: 70/100
Sementes concluídas: 80/100
Sementes concluídas: 90/100
Sementes concluídas: 100/100

      HIT6_CONDICIONAL_PCT  GANHO_CONDICIONAL_PP
mean                 66.21                 24.04
std                   3.12                  3.12
min                  57.05                 14.87
max                  73.83                 31.65

### Usando 3 metricas (25 Dezenas):
#### Mahalanobis -> Maior distância ao vetor de frequências
#### Distância ao vizinho mais próximo -> Maior distância mínima aos outros três grupos
#### Distância máxima aos demais -> Maior distância ao candidato mais distante

In [34]:
import fac_diagnostico_tres_metricas as fac_tres

comparacao = fac_tres.comparar_metricas(
    df,
    seeds=range(100),
    progresso=10,
)

display(comparacao["resumo"].round(2))

MÉTRICA: mahalanobis
Sementes concluídas: 10/100
Sementes concluídas: 20/100
Sementes concluídas: 30/100
Sementes concluídas: 40/100
Sementes concluídas: 50/100
Sementes concluídas: 60/100
Sementes concluídas: 70/100
Sementes concluídas: 80/100
Sementes concluídas: 90/100
Sementes concluídas: 100/100

MÉTRICA: vizinho_proximo
Sementes concluídas: 10/100
Sementes concluídas: 20/100
Sementes concluídas: 30/100
Sementes concluídas: 40/100
Sementes concluídas: 50/100
Sementes concluídas: 60/100
Sementes concluídas: 70/100
Sementes concluídas: 80/100
Sementes concluídas: 90/100
Sementes concluídas: 100/100

MÉTRICA: distancia_maxima
Sementes concluídas: 10/100
Sementes concluídas: 20/100
Sementes concluídas: 30/100
Sementes concluídas: 40/100
Sementes concluídas: 50/100
Sementes concluídas: 60/100
Sementes concluídas: 70/100
Sementes concluídas: 80/100
Sementes concluídas: 90/100
Sementes concluídas: 100/100

,REGRA,N_SEEDS,HIT6_MEDIA,HIT6_STD,HIT6_MIN,HIT6_MAX,GANHO_VS_BASE_PP,GANHO_LOCAL_MENOR_ACE_PP,DIF_VS_TOP20_HISTORICO_66_59_PP
0,mahalanobis,100,46.60,1.85,41.61,51.01,4.42,7.28,-19.99
1,vizinho_proximo,100,60.72,2.98,53.69,68.46,18.55,8.95,-5.87
2,distancia_maxima,100,47.87,3.86,40.27,59.06,5.69,2.05,-18.72

In [36]:
display(comparacao["repeticoes"])

,REGRA,SEED,JOGOS_PROCESSADOS,JOGOS_COM_ALVO_ORIGINAL,JOGOS_SEM_ALVO_ORIGINAL,GRUPOS_ORIGINAIS,GRUPOS_FINAIS,ALVOS_ORIGINAIS,ALVOS_SOBREVIVENTES,JOGOS_COM_ALVO_FINAL,...,ACE_MAX_FINAL_MEDIO,JOGOS_COM_ACE_MAX_PRESERVADO,BLOCOS_AVALIADOS,REMOCOES_COM_MENOR_ACE_PCT,BLOCOS_COM_UNICO_ALVO,BLOCOS_QUE_PERDERAM_UNICO_ALVO,BLOCOS_COM_ACES_DIFERENTES,MENOR_ACE_REMOVIDO_BLOCOS_INFORMATIVOS_PCT,BASELINE_LOCAL_MENOR_ACE_PCT,GANHO_LOCAL_MENOR_ACE_PP
0,mahalanobis,0.0,156.0,149.0,7.0,3432.0,936.0,272.0,90.0,71.0,...,13.391026,70.0,2496.0,69.871795,348.0,79.0,1672.0,55.023923,48.744019,6.279904
1,mahalanobis,1.0,156.0,149.0,7.0,3432.0,936.0,272.0,92.0,71.0,...,13.435897,74.0,2496.0,70.512821,366.0,80.0,1696.0,56.603774,48.732311,7.871462
2,mahalanobis,2.0,156.0,149.0,7.0,3432.0,936.0,272.0,92.0,72.0,...,13.429487,75.0,2496.0,70.673077,361.0,78.0,1676.0,56.324582,48.075776,8.248807
3,mahalanobis,3.0,156.0,149.0,7.0,3432.0,936.0,272.0,89.0,70.0,...,13.416667,70.0,2496.0,69.951923,367.0,80.0,1687.0,55.542383,48.014226,7.528156
4,mahalanobis,4.0,156.0,149.0,7.0,3432.0,936.0,272.0,86.0,64.0,...,13.384615,67.0,2496.0,69.831731,368.0,87.0,1684.0,55.285036,48.396675,6.888361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,distancia_maxima,95.0,156.0,149.0,7.0,3432.0,936.0,272.0,77.0,69.0,...,13.391026,71.0,2496.0,66.907051,356.0,82.0,1693.0,51.210868,48.995865,2.215003
296,distancia_maxima,96.0,156.0,149.0,7.0,3432.0,936.0,272.0,86.0,74.0,...,13.461538,75.0,2496.0,66.987179,396.0,77.0,1699.0,51.500883,49.396704,2.104179
297,distancia_maxima,97.0,156.0,149.0,7.0,3432.0,936.0,272.0,70.0,66.0,...,13.391026,67.0,2496.0,67.868590,364.0,83.0,1673.0,52.062164,48.640167,3.421996
298,distancia_maxima,98.0,156.0,149.0,7.0,3432.0,936.0,272.0,79.0,66.0,...,13.448718,71.0,2496.0,66.105769,368.0,84.0,1675.0,49.492537,48.716418,0.776119
299,distancia_maxima,99.0,156.0,149.0,7.0,3432.0,936.0,272.0,73.0,60.0,...,13.346154,61.0,2496.0,66.826923,345.0,89.0,1678.0,50.655542,48.971990,1.683552